// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RecordStatus {
    "id": string;
    "exitCode": number;
    "errMsg": string;
    "running": boolean;
}
