// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DataStore {
    "id": string;
    "name": string;
    "kind": string;
    "target": string;
    "args": string;
    "workDir": string;
    "env": string[] | null;
    "mode": string;
    "encoding": string;
    "cols": number;
    "rows": number;
    "autoStart": boolean;
    "sortOrder": number;
}

export interface Settings {
    "language": string;
    "theme": string;
    "startOnBoot": boolean;
}
