// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExitPayload 是 "session:exited" 事件的数据类型。
 * 不能直接发 executor.ExitResult——它的 Err 字段是 error 接口，不能过 JSON。
 */
export interface ExitPayload {
    "id": string;
    "code": number;
    "errMsg": string;
}

/**
 * OutputPayload 是 "session:output" 事件的数据类型。
 * 导出是因为 main.go 的 init() 里要把它注册给 RegisterEvent——
 * wails 的事件数据是精确类型匹配的，注册的类型必须和 Emit 传的类型一模一样，
 * 否则事件会被 Cancel 掉，前端一条也收不到。
 */
export interface OutputPayload {
    "id": string;
    "text": string;
}
