// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hub$0 from "./internal/exec/hub/models.js";

export function ListStatus(): $CancellablePromise<hub$0.RecordStatus[] | null> {
    return $Call.ByID(2406979344);
}

export function ResizeSession(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3012637930, id, cols, rows);
}

export function RestartSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(425209671, id);
}

export function StartSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3998795598, id);
}

export function StopAllSessions(): $CancellablePromise<void> {
    return $Call.ByID(3765323104);
}

export function StopSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(871503534, id);
}

export function WriteSession(id: string, data: string): $CancellablePromise<number> {
    return $Call.ByID(1056708111, id, data);
}
