// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/exec/store/models.js";

export function CreateSession(d: store$0.DataStore): $CancellablePromise<string> {
    return $Call.ByID(4268836328, d);
}

export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3139028285, id);
}

export function GetSession(id: string): $CancellablePromise<store$0.DataStore> {
    return $Call.ByID(2478346128, id);
}

export function GetSettings(): $CancellablePromise<store$0.Settings> {
    return $Call.ByID(2899298809);
}

export function ListSessions(): $CancellablePromise<store$0.DataStore[] | null> {
    return $Call.ByID(168441053);
}

export function SaveSettings(settings: store$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(1891988456, settings);
}

export function UpdateSession(id: string, d: store$0.DataStore): $CancellablePromise<string> {
    return $Call.ByID(1645521419, id, d);
}
