// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetAppWorkDir(): $CancellablePromise<string> {
    return $Call.ByID(166898860);
}

export function GetStartOnBootStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(3318750532);
}

/**
 * OpenScriptDir 用于打开脚本文件目录
 */
export function OpenScriptDir(id: string): $CancellablePromise<void> {
    return $Call.ByID(2500555507, id);
}

/**
 * OpenWorkDir 用于打开工作目录
 */
export function OpenWorkDir(id: string): $CancellablePromise<void> {
    return $Call.ByID(2999070909, id);
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3338230571);
}

/**
 * ResolveSpecCommandLine 用于回显实际的命令行
 */
export function ResolveSpecCommandLine(id: string): $CancellablePromise<string> {
    return $Call.ByID(2256642649, id);
}

/**
 * ResolveWorkDir 用于复制工作目录路径
 */
export function ResolveWorkDir(id: string): $CancellablePromise<string> {
    return $Call.ByID(3897877379, id);
}

export function SetStartOnBoot(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1715434118, enabled);
}
