// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hub$0 from "../exec/hub/models.js";

export function ListStatus(): $CancellablePromise<hub$0.RecordStatus[] | null> {
    return $Call.ByID(291041921);
}

export function ResizeSession(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3713270193, id, cols, rows);
}

export function RestartSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(802803738, id);
}

export function StartSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1650137335, id);
}

export function StopAllSessions(): $CancellablePromise<void> {
    return $Call.ByID(3318317055);
}

export function StopSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(740482977, id);
}

export function WriteSession(id: string, data: string): $CancellablePromise<number> {
    return $Call.ByID(476592342, id, data);
}
