// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
import * as GreetService from "./greetservice.js";
import * as HubService from "./hubservice.js";
import * as StoreService from "./storeservice.js";
import * as XtermDemoService from "./xtermdemoservice.js";
export {
    AppService,
    GreetService,
    HubService,
    StoreService,
    XtermDemoService
};
